[window]
dynamic_padding = true
opacity = 0.9

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
size = 11

[colors]
cursor = { text = "#0d0e0c", cursor = "#c8b6b8" }

[colors.primary]
background = "#ffffff"
foreground = "#6b6b6b"
