[general]
import = [ "~/.cache/wal/colors-alacritty.toml" ]

[window]
dynamic_padding = true
opacity = 0.75

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
size = 11

[colors]
cursor = { text = "#0d0e0c", cursor = "#c8b6b8" }
