soft-serve:
    admin-key: ENC[AES256_GCM,data:hkkSn73/qdVtIQwGASmRo4NTL3ur4Mb5sR75hKzScZqR+tXu62qCkT1ox4pjXGU/qo+woz6A8A6gEsyFfzh0COIuguEpQmpEhIc19XgzLNIlFGEUXJU7oqVtsaEd,iv:X//JLChSZowxav3tZd9QIr1N1qe0zuHWdX2rSTwB5FM=,tag:jU3Hq34wS5Rqwf96EEgvuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gcllyspzkxqrhqvdqm3vcafpl7esd6de2nlcemfsa323cvtcp3tqfej2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZTJ3L1hrblFLalZDV1o2
            Zko4c0NDbWZBZlBrYU5peFJHd3JraW1tUGxVCnhZVGhqTit3c0RENkFXblpRbW9R
            RHNQRmhyaUpweUdGS1ZMSm9Kc0JwN1UKLS0tIHd3dEtXdUM1Z1d1Z2hkK2ZsYW83
            VjNkb2RpSzZJdnV3Vitxb1ZXSGthbm8KPeGICQ2VVqUk4df0UPfuJ38/mcfRcR70
            iWmBXLeIZkrb112G/rcYkTW1mhv+XVf5vAGW6eiN6gM/iWgNZIr0JA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1stg9wuxesdfv8cqcqvvs3eg8v2xv9rt0x4h3etqz80ngcwdt5g8q03wk0v
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArWk03SkNpNzV0c250Mm1D
            TTJQYW1aSUoxNDkxenBvNFF1TWtObllaT2pBCjl0dHV6NXgvS3FKeml5WmZFM0hY
            V2dPVFNFeFRlNmVqUElXNGtDMm9XWVkKLS0tIHJIaXFVRzh4dEZQUERpdFAzK1dN
            eHhxaXM0a1JYRHVoN1JuWjg3YUYvTG8K6DMdZq8TDPZ7KQAP32dKjXiiMV9QML9+
            3mxdbz9FzjRQrJz8peG+e8C6YrR6B2H8h9cE4/+1Y3iccToUHcIIJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T17:41:39Z"
    mac: ENC[AES256_GCM,data:5z9LGfm5CP9ukH1ixdak9aHBO0cG5XlWzotInVO3n9hkP35x62VYNeimRC3OFUk7x0ocF4LcIatBGnQlH7u7HaAVDgyGBp395ZsZ6johD7TwDBnhShWprNf9gZT+CdP9fUrdGVphFkL0Er2mnjuNDpFsvbcaTjRn202tDW3RGKA=,iv:azTpxfbUFy+gDO3m8g1NK3K9eARnIk5bvSlS4xSBhOg=,tag:CZu6f0HwJwV9futo7rqmBw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
