softserve:
    key: ENC[AES256_GCM,data:nZiHV1B6uoqM0vCh,iv:4JSk88Gzsxjw7L69eiNrGX4cgoW9YMLFb35hCXCYzxM=,tag:dbRvcVKwsfQrHFWY2awjLQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gcllyspzkxqrhqvdqm3vcafpl7esd6de2nlcemfsa323cvtcp3tqfej2gr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQkZEcGRseUNobTBkMDdz
            bW9paDMyN3pMWkszbmhBTFpUeXFXcGVDOVc4CldRbEthVVh5b1Q5YkhrVkc0dzRR
            TTc4cVlpMjRJaUYyOEdSTjlYbS9hOWsKLS0tIEUzYTFxYTJqcVowSnBOQ2tqUlpx
            WWpNcW1DTHAybGdzMGVCcEFOU0wwOTAKgHyPk0G9N3yNcCeG8TDSWYyP78mkSHxX
            z9IjA6ybhBEeq7Swl6xuXjVr9fcM1Lu83dap79cdTwAhtW5Wfc8ZsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-29T15:40:04Z"
    mac: ENC[AES256_GCM,data:0tzyGgIHIt+iroxHr7Wt+4kGWQg4tIjxy2bmgJMxPvwY5QcCAR3878aIf66xUhwJ3VmPE5DnGVT+2TscZ276K1u0QnzdIShYEfZ8ThJMB8ElyaMwS2qJjHPFARJNQKi9IlvEl1y6xUtbSeb0IuwN0CU2tf5DE9V1XdMZcRn0EGo=,iv:W1rPTAD+3OAPDcgoT/DJIoQoRZ1BaDxlS/f6o96lXiQ=,tag:42kCAgEC0p//8/9OcGOdyQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
