keys:
  - &jaam age1gcllyspzkxqrhqvdqm3vcafpl7esd6de2nlcemfsa323cvtcp3tqfej2gr
  - &alajaam age1stg9wuxesdfv8cqcqvvs3eg8v2xv9rt0x4h3etqz80ngcwdt5g8q03wk0v
creation_rules:
  - path_regex: .secrets.yaml
    key_groups:
    - age:
      - *jaam
      - *alajaam
