#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

USER="mart"
CONF="/home/$USER/.config"
DOTS="/home/$USER/git/dotfiles/homes/modules"

PKGS_CORE="base base-devel linux-lts linux-firmware intel-ucode"
PKGS_COMMON="sudo man-db bash-completion git curl wget neovim vim tmux openssl openssh sshfs networkmanager wol socat net-tools inotify-tools expect"
PKGS_EXTRA="fastfetch ripgrep cargo cmake make nodejs gcc uv jq zip unzip cloudflared tree docker docker-compose docker-buildx containerd"
PKGS_HARDWARE="pipewire pipewire-alsa pipewire-pulse wireplumber bluez bluez-utils ccid pcsclite brightnessctl intel-undervolt tlp"
PKGS_HYPRLAND="hyprland hypridle hyprpaper hyprlock eww wl-clipboard gammastep greetd grim slurp rofi rofi-emoji dunst"
PKGS_DESKTOP="alacritty firefox zoom slack-desktop qdigidoc4 web-eid-native web-eid-firefox noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-jetbrains-mono-nerd"

if ! id -u aur > /dev/null 2>&1; then
    echo -e "[${BOLDGREEN}aur user${ENDCOLOR}]"

    groupadd -f aur

    useradd -m aur
    usermod -a -G aur aur

    echo "aur   ALL = (root) NOPASSWD: /usr/bin/makepkg, /usr/bin/pacman" > /etc/sudoers.d/aur
fi

if ! command -v yay &> /dev/null; then
    echo -e "[${BOLDGREEN}aur helper${ENDCOLOR}]"

    pacman -S --needed --noconfirm base-devel git
    su aur -c "
        git clone https://aur.archlinux.org/yay.git /tmp/yay

        pushd /tmp/yay
        makepkg -si --needed --noconfirm
        popd

        rm -rf /tmp/yay
    "
fi

echo -e "[${BOLDGREEN}packages${ENDCOLOR}]"

su aur -c "yay -S --needed --noconfirm $PKGS_CORE $PKGS_COMMON $PKGS_EXTRA $PKGS_HYPRLAND $PKGS_HARDWARE $PKGS_DESKTOP"

echo -e "[${BOLDGREEN}groups${ENDCOLOR}]"

groupadd -f docker
groupadd -f network

usermod -a -G docker $USER
usermod -a -G network $USER

echo -e "[${BOLDGREEN}services${ENDCOLOR}]"

systemctl enable tlp.service
systemctl enable pcscd.service
systemctl enable docker.service
systemctl enable NetworkManager
systemctl enable bluetooth.service
systemctl enable intel-undervolt.service

echo -e "[${BOLDGREEN}configs${ENDCOLOR}]"

rm -rf /etc/greetd
mkdir --parents /etc/greetd
cat << EOF > /etc/greetd/config.toml
[terminal]
vt = 1

[default_session]
command = "hyprland"
user = "${USER}"
EOF

su "$USER" -c "
    ln -sf $DOTS/bash/.bashrc /home/$USER/.bashrc
    ln -sf $DOTS/alacritty $CONF
    ln -sf $DOTS/rofi $CONF
    ln -sf $DOTS/nvim $CONF
    ln -sf $DOTS/tmux $CONF
    ln -sf $DOTS/hypr $CONF
    ln -sf $DOTS/eww $CONF
"
