#!/bin/bash

BOLDGREEN="\e[1;32m"
ENDCOLOR="\e[0m"

if [[ -z $1 ]]; then
    echo "setup USER"
    exit 1
fi

USER="mart"
HOME="/home/$USER"
CONF="$HOME/.config"
DOTS="$HOME/git/dotfiles"

PKGS_HYPRLAND="hyprland hypridle hyprpaper hyprlock eww wl-clipboard alacritty gammastep greetd grim slurp rofi rofi-emoji socat dunst"
PKGS_HARDWARE="pipewire pipewire-alsa pipewire-pulse wireplumber pamixer bluez bluez-utils ccid pcsclite brightnessctl"
PKGS_DESKTOP="alacritty firefox zoom slack-desktop qdigidoc4 web-eid-native web-eid-firefox"
PKGS_FONTS="noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-jetbrains-mono-nerd"

echo -e "[${BOLDGREEN}packages${ENDCOLOR}]"

su aur -c "yay -S --needed --noconfirm $PKGS_HYPRLAND $PKGS_HARDWARE $PKGS_DESKTOP $PKGS_FONTS"

echo -e "[${BOLDGREEN}services${ENDCOLOR}]"

systemctl enable pcscd.service
systemctl enable bluetooth.service

echo -e "[${BOLDGREEN}configs${ENDCOLOR}]"

ln -sf $DOTS/greetd/config.toml /etc/greetd/config.toml

su "$USER" -c "
    ln -sf $DOTS/hypr $CONF
    ln -sf $DOTS/eww $CONF

    ln -sf $DOTS/alacritty $CONF
    ln -sf $DOTS/rofi $CONF
"
