[urgency_low]
background = "{{ colors.background.default.hex }}"
foreground = "{{ colors.on_background.default.hex }}"
frame_color = "{{ colors.on_background.default.hex }}"
default_icon = "~/.config/dunst/icons/bell-low.svg"

[urgency_normal]
background = "{{ colors.background.default.hex }}"
foreground = "#f4bf75"
frame_color = "#f4bf75"
default_icon = "~/.config/dunst/icons/bell-normal.svg"

[urgency_critical]
background = "{{ colors.background.default.hex }}"
foreground = "#ac4142"
frame_color = "#ac4142"
default_icon = "~/.config/dunst/icons/bell-critical.svg"
