[urgency_low]
background = "{{ colors.background.default.hex }}",
foreground = "{{ colors.on_background.default.hex }}",
frame_color = "{{ base16.base05.default.hex }}"
default_icon = "~/.config/dunst/icons/bell-low.svg"

[urgency_normal]
background = "{{ colors.background.default.hex }}",
foreground = "{{ base16.base03.default.hex }}"
frame_color = "{{ base16.base03.default.hex }}"
default_icon = "~/.config/dunst/icons/bell-normal.svg"

[urgency_critical]
background = "{{ colors.background.default.hex }}",
foreground = "{{ base16.base01.default.hex }}"
frame_color = "{{ base16.base01.default.hex }}"
default_icon = "~/.config/dunst/icons/bell-critical.svg"
