#!/usr/bin/env bash

use_nvm() {
    if [ -e $HOME/.nvm/nvm.sh ]; then
        source $HOME/.nvm/nvm.sh
        nvm use $1
    fi
}

layout_maven() {
    lombok=$HOME/.m2/repository/org/projectlombok/lombok/1.18.30/lombok-1.18.30.jar
    if [ -e $lombok ]; then
        export JDTLS_JVM_ARGS="-javaagent:$lombok"
    fi
}

layout_pnpm() {
    PNPM_HOME=$HOME/.local/share/pnpm
    if [ -d $PNPM_HOME ]; then
        PATH_add $PNPM_HOME
        export PNPM_HOME
    fi
}

layout_uv() {
    VIRTUAL_ENV=$(pwd)/.venv
    if [ ! -d $VIRTUAL_ENV ]; then
        uv venv
    fi

    PATH_add $VIRTUAL_ENV/bin
    export VIRTUAL_ENV
    export UV_ACTIVE=1
}
