#!/usr/bin/env bash

use_nvm() {
    source $HOME/.nvm/nvm.sh
    nvm use $1
}

use_conda() {
    PATH_add $HOME/miniconda3/bin
    eval "$(conda shell.zsh hook)"
    conda activate $1
}

layout_bun() {
    export BUN_INSTALL=$HOME/.bun
    PATH_add $BUN_INSTALL/bin
}

layout_pnpm() {
    export PNPM_HOME=$HOME/.local/share/pnpm
    PATH_add $PNPM_HOME
}

layout_uv() {
    VIRTUAL_ENV=$(pwd)/.venv
    source $VIRTUAL_ENV/bin/activate
    export UV_ACTIVE=1
}
