$opaque     = rgba(ffffff80)
$background = rgb(ffffff)
$foreground = rgb(4d4d4c)
$color0     = rgb(151515)
$color1     = rgb(ac4142)
$color2     = rgb(90a959)
$color3     = rgb(f4bf75)
$color4     = rgb(6a9fb5)
$color5     = rgb(aa759f)
$color6     = rgb(75b5aa)
$color7     = rgb(d0d0d0)
$color8     = rgb(505050)
$color9     = rgb(ac4142)
$color10    = rgb(90a959)
$color11    = rgb(f4bf75)
$color12    = rgb(6a9fb5)
$color13    = rgb(aa759f)
$color14    = rgb(75b5aa)
$color15    = rgb(f5f5f5)
