$wallpaper  = ~/.cache/rice/walls/light-centered-dude.jpg
$background = rgb(f9f9ff)
$foreground = rgb(1a1b20)
$color0     = rgb(ffffff)
$color1     = rgb(e6e6e6)
$color2     = rgb(cdcdcd)
$color3     = rgb(b5b5b5)
$color4     = rgb(9c9c9c)
$color5     = rgb(838383)
$color6     = rgb(6a6a6a)
$color7     = rgb(515151)
$color8     = rgb(ffffff)
$color9     = rgb(ffffff)
$color10    = rgb(ffffff)
$color11    = rgb(ffffff)
$color12    = rgb(ffffff)
$color13    = rgb(ffffff)
$color14    = rgb(ffffff)
$color15    = rgb(ffffff)
