source = ~/.cache/hellwal/colors.conf

background {
    path = $wallpaper
}

input-field {
    font_family = JetBrainsMono
    font_color = rgb(000000)
    fail_color = rgba(00000000)
    inner_color = rgba(00000000)
    outer_color = rgba(00000000)
    check_color = rgba(00000000)
}
