source = ~/.config/hypr/colors.conf

general {
    ignore_empty_input = true
    fail_timeout = 500
}

background {
    path = ~/.cache/rice/walls/current
    blur_passes = 2
    blur_size = 2
}

input-field {
    font_family = JetBrainsMono NerdFont
    font_color = $foreground

    inner_color = $opaque
    outer_color = $opaque
    check_color = rgb(f4bf75)
    fail_color = rgb(ac4142)

    outline_thickness = 1
    position = 0, -35%
    size = 250, 50
    rounding = 8
}
