source = ~/.config/hypr/colors.conf

general {
    ignore_empty_input = true
    fail_timeout = 500
}

background {
    path = $wallpaper
    blur_passes = 2
    blur_size = 2
}

input-field {
    font_family = JetBrainsMono
    font_color = $foreground

    outer_color = $foreground
    inner_color = $background
    check_color = rgb(f4bf75)
    fail_color = rgb(ac4142)

    outline_thickness = 1
    position = 0, -35%
    size = 400, 75
    rounding = 0
}
