[urgency_low]
background = "#ffffff"
foreground = "#4d4d4c"
frame_color = "#4d4d4c"
new_icon = "~/.config/dunst/icons/bell-low.svg"

[urgency_normal]
background = "#ffffff"
foreground = "#4d4d4c"
frame_color = "#4d4d4c"
new_icon = "~/.config/dunst/icons/bell-normal.svg"

[urgency_critical]
background = "#ffffff"
foreground = "#ac4142"
frame_color = "#ac4142"
new_icon = "~/.config/dunst/icons/bell-critical.svg"
