[urgency_low]
background = "#f5f5f5"
foreground = "#90a959"
frame_color = "#90a959"
new_icon = "~/.config/dunst/icons/bell-low.svg"

[urgency_normal]
background = "#f5f5f5"
foreground = "#151515"
frame_color = "#151515"
new_icon = "~/.config/dunst/icons/bell-normal.svg"

[urgency_critical]
background = "#f5f5f5"
foreground = "#ac4142"
frame_color = "#ac4142"
new_icon = "~/.config/dunst/icons/bell-critical.svg"
