name: ci

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - '**'

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - run: find . -name '*.sh' -exec shellcheck {} +
